services:
  proxy_server:
    restart: always
    image: nginx
    ports:
      - 9080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  mockserver:
    restart: always
    image: mockoon/cli:2.4.0
    ports:
      - 3000:3000
    command: "-d https://raw.githubusercontent.com/conekta/openapi/20230613/mocks/conekta_api.json -p 3000 --log-transaction"
    healthcheck:
      test: "wget -qO - http://mockserver:3000/ping"
      interval: 5s
      timeout: 10s
      retries: 20