/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.conekta.JSON;


/**
 * api keys model
 */
@JsonPropertyOrder({
  ApiKeyResponse.JSON_PROPERTY_ACTIVE,
  ApiKeyResponse.JSON_PROPERTY_CREATED_AT,
  ApiKeyResponse.JSON_PROPERTY_UPDATED_AT,
  ApiKeyResponse.JSON_PROPERTY_DEACTIVATED_AT,
  ApiKeyResponse.JSON_PROPERTY_LAST_USED_AT,
  ApiKeyResponse.JSON_PROPERTY_DESCRIPTION,
  ApiKeyResponse.JSON_PROPERTY_ID,
  ApiKeyResponse.JSON_PROPERTY_LIVEMODE,
  ApiKeyResponse.JSON_PROPERTY_OBJECT,
  ApiKeyResponse.JSON_PROPERTY_PREFIX,
  ApiKeyResponse.JSON_PROPERTY_ROLE
})
@JsonTypeName("api_key_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ApiKeyResponse {
  public static final String JSON_PROPERTY_ACTIVE = "active";
  @javax.annotation.Nullable
  private Boolean active;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private Long createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nullable
  private Long updatedAt;

  public static final String JSON_PROPERTY_DEACTIVATED_AT = "deactivated_at";
  @javax.annotation.Nullable
  private Long deactivatedAt;

  public static final String JSON_PROPERTY_LAST_USED_AT = "last_used_at";
  @javax.annotation.Nullable
  private Long lastUsedAt;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_LIVEMODE = "livemode";
  @javax.annotation.Nullable
  private Boolean livemode;

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nullable
  private String _object;

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @javax.annotation.Nullable
  private String prefix;

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nullable
  private String role;

  public ApiKeyResponse() { 
  }

  public ApiKeyResponse active(@javax.annotation.Nullable Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Indicates if the api key is active
   * @return active
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(@javax.annotation.Nullable Boolean active) {
    this.active = active;
  }


  public ApiKeyResponse createdAt(@javax.annotation.Nullable Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Unix timestamp in seconds of when the api key was created
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable Long createdAt) {
    this.createdAt = createdAt;
  }


  public ApiKeyResponse updatedAt(@javax.annotation.Nullable Long updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Unix timestamp in seconds of when the api key was last updated
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable Long updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ApiKeyResponse deactivatedAt(@javax.annotation.Nullable Long deactivatedAt) {
    this.deactivatedAt = deactivatedAt;
    return this;
  }

  /**
   * Unix timestamp in seconds of when the api key was deleted
   * @return deactivatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEACTIVATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDeactivatedAt() {
    return deactivatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_DEACTIVATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeactivatedAt(@javax.annotation.Nullable Long deactivatedAt) {
    this.deactivatedAt = deactivatedAt;
  }


  public ApiKeyResponse lastUsedAt(@javax.annotation.Nullable Long lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
    return this;
  }

  /**
   * Unix timestamp in seconds with the api key was used
   * @return lastUsedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_USED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLastUsedAt() {
    return lastUsedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_USED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUsedAt(@javax.annotation.Nullable Long lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
  }


  public ApiKeyResponse description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * A name or brief explanation of what this api key is used for
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public ApiKeyResponse id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the api key
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ApiKeyResponse livemode(@javax.annotation.Nullable Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

  /**
   * Indicates if the api key is in production
   * @return livemode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIVEMODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLivemode() {
    return livemode;
  }


  @JsonProperty(value = JSON_PROPERTY_LIVEMODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLivemode(@javax.annotation.Nullable Boolean livemode) {
    this.livemode = livemode;
  }


  public ApiKeyResponse _object(@javax.annotation.Nullable String _object) {
    this._object = _object;
    return this;
  }

  /**
   * Object name, value is &#39;api_key&#39;
   * @return _object
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(@javax.annotation.Nullable String _object) {
    this._object = _object;
  }


  public ApiKeyResponse prefix(@javax.annotation.Nullable String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * The first few characters of the authentication_token
   * @return prefix
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrefix() {
    return prefix;
  }


  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrefix(@javax.annotation.Nullable String prefix) {
    this.prefix = prefix;
  }


  public ApiKeyResponse role(@javax.annotation.Nullable String role) {
    this.role = role;
    return this;
  }

  /**
   * Indicates if the api key is private or public
   * @return role
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRole() {
    return role;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRole(@javax.annotation.Nullable String role) {
    this.role = role;
  }


  /**
   * Return true if this api_key_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiKeyResponse apiKeyResponse = (ApiKeyResponse) o;
    return Objects.equals(this.active, apiKeyResponse.active) &&
        Objects.equals(this.createdAt, apiKeyResponse.createdAt) &&
        Objects.equals(this.updatedAt, apiKeyResponse.updatedAt) &&
        Objects.equals(this.deactivatedAt, apiKeyResponse.deactivatedAt) &&
        Objects.equals(this.lastUsedAt, apiKeyResponse.lastUsedAt) &&
        Objects.equals(this.description, apiKeyResponse.description) &&
        Objects.equals(this.id, apiKeyResponse.id) &&
        Objects.equals(this.livemode, apiKeyResponse.livemode) &&
        Objects.equals(this._object, apiKeyResponse._object) &&
        Objects.equals(this.prefix, apiKeyResponse.prefix) &&
        Objects.equals(this.role, apiKeyResponse.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, createdAt, updatedAt, deactivatedAt, lastUsedAt, description, id, livemode, _object, prefix, role);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiKeyResponse {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deactivatedAt: ").append(toIndentedString(deactivatedAt)).append("\n");
    sb.append("    lastUsedAt: ").append(toIndentedString(lastUsedAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

