/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.conekta.model.ChargebackEvidenceFileResponse;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.conekta.JSON;


/**
 * Result of a batch evidence file upload
 */
@JsonPropertyOrder({
  ChargebackFilesBatchResponse.JSON_PROPERTY_FILES
})
@JsonTypeName("chargeback_files_batch_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ChargebackFilesBatchResponse {
  public static final String JSON_PROPERTY_FILES = "files";
  @javax.annotation.Nullable
  private List<ChargebackEvidenceFileResponse> files = new ArrayList<>();

  public ChargebackFilesBatchResponse() { 
  }

  public ChargebackFilesBatchResponse files(@javax.annotation.Nullable List<ChargebackEvidenceFileResponse> files) {
    this.files = files;
    return this;
  }

  public ChargebackFilesBatchResponse addFilesItem(ChargebackEvidenceFileResponse filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

  /**
   * Get files
   * @return files
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ChargebackEvidenceFileResponse> getFiles() {
    return files;
  }


  @JsonProperty(value = JSON_PROPERTY_FILES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiles(@javax.annotation.Nullable List<ChargebackEvidenceFileResponse> files) {
    this.files = files;
  }


  /**
   * Return true if this chargeback_files_batch_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargebackFilesBatchResponse chargebackFilesBatchResponse = (ChargebackFilesBatchResponse) o;
    return Objects.equals(this.files, chargebackFilesBatchResponse.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(files);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargebackFilesBatchResponse {\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

