/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.conekta.model.CreateCompanyRequestBankAccountInfo;
import com.conekta.model.CreateCompanyRequestComercialInfo;
import com.conekta.model.CreateCompanyRequestFiscalInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.conekta.JSON;


/**
 * CreateCompanyRequest
 */
@JsonPropertyOrder({
  CreateCompanyRequest.JSON_PROPERTY_NAME,
  CreateCompanyRequest.JSON_PROPERTY_TYPE_COMPANY,
  CreateCompanyRequest.JSON_PROPERTY_COMERCIAL_INFO,
  CreateCompanyRequest.JSON_PROPERTY_FISCAL_INFO,
  CreateCompanyRequest.JSON_PROPERTY_BANK_ACCOUNT_INFO
})
@JsonTypeName("Create_Company_Request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CreateCompanyRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TYPE_COMPANY = "type_company";
  @javax.annotation.Nullable
  private String typeCompany;

  public static final String JSON_PROPERTY_COMERCIAL_INFO = "comercial_info";
  @javax.annotation.Nullable
  private CreateCompanyRequestComercialInfo comercialInfo;

  public static final String JSON_PROPERTY_FISCAL_INFO = "fiscal_info";
  @javax.annotation.Nullable
  private CreateCompanyRequestFiscalInfo fiscalInfo;

  public static final String JSON_PROPERTY_BANK_ACCOUNT_INFO = "bank_account_info";
  @javax.annotation.Nullable
  private CreateCompanyRequestBankAccountInfo bankAccountInfo;

  public CreateCompanyRequest() { 
  }

  public CreateCompanyRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the company.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateCompanyRequest typeCompany(@javax.annotation.Nullable String typeCompany) {
    this.typeCompany = typeCompany;
    return this;
  }

  /**
   * The type of company, &#39;owner&#39;
   * @return typeCompany
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE_COMPANY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTypeCompany() {
    return typeCompany;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE_COMPANY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeCompany(@javax.annotation.Nullable String typeCompany) {
    this.typeCompany = typeCompany;
  }


  public CreateCompanyRequest comercialInfo(@javax.annotation.Nullable CreateCompanyRequestComercialInfo comercialInfo) {
    this.comercialInfo = comercialInfo;
    return this;
  }

  /**
   * Get comercialInfo
   * @return comercialInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMERCIAL_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateCompanyRequestComercialInfo getComercialInfo() {
    return comercialInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_COMERCIAL_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComercialInfo(@javax.annotation.Nullable CreateCompanyRequestComercialInfo comercialInfo) {
    this.comercialInfo = comercialInfo;
  }


  public CreateCompanyRequest fiscalInfo(@javax.annotation.Nullable CreateCompanyRequestFiscalInfo fiscalInfo) {
    this.fiscalInfo = fiscalInfo;
    return this;
  }

  /**
   * Get fiscalInfo
   * @return fiscalInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FISCAL_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateCompanyRequestFiscalInfo getFiscalInfo() {
    return fiscalInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_FISCAL_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiscalInfo(@javax.annotation.Nullable CreateCompanyRequestFiscalInfo fiscalInfo) {
    this.fiscalInfo = fiscalInfo;
  }


  public CreateCompanyRequest bankAccountInfo(@javax.annotation.Nullable CreateCompanyRequestBankAccountInfo bankAccountInfo) {
    this.bankAccountInfo = bankAccountInfo;
    return this;
  }

  /**
   * Get bankAccountInfo
   * @return bankAccountInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BANK_ACCOUNT_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateCompanyRequestBankAccountInfo getBankAccountInfo() {
    return bankAccountInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_BANK_ACCOUNT_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBankAccountInfo(@javax.annotation.Nullable CreateCompanyRequestBankAccountInfo bankAccountInfo) {
    this.bankAccountInfo = bankAccountInfo;
  }


  /**
   * Return true if this Create_Company_Request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCompanyRequest createCompanyRequest = (CreateCompanyRequest) o;
    return Objects.equals(this.name, createCompanyRequest.name) &&
        Objects.equals(this.typeCompany, createCompanyRequest.typeCompany) &&
        Objects.equals(this.comercialInfo, createCompanyRequest.comercialInfo) &&
        Objects.equals(this.fiscalInfo, createCompanyRequest.fiscalInfo) &&
        Objects.equals(this.bankAccountInfo, createCompanyRequest.bankAccountInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, typeCompany, comercialInfo, fiscalInfo, bankAccountInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCompanyRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    typeCompany: ").append(toIndentedString(typeCompany)).append("\n");
    sb.append("    comercialInfo: ").append(toIndentedString(comercialInfo)).append("\n");
    sb.append("    fiscalInfo: ").append(toIndentedString(fiscalInfo)).append("\n");
    sb.append("    bankAccountInfo: ").append(toIndentedString(bankAccountInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

