/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.conekta.model.CustomerShippingContactsRequestAddress;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.conekta.JSON;


/**
 * [Shipping](https://developers.conekta.com/v2.2.0/reference/createcustomershippingcontacts) details, required in case of sending a shipping. If we do not receive a shipping_contact on the order, the default shipping_contact of the customer will be used.
 */
@JsonPropertyOrder({
  CustomerUpdateShippingContactsRequest.JSON_PROPERTY_PHONE,
  CustomerUpdateShippingContactsRequest.JSON_PROPERTY_RECEIVER,
  CustomerUpdateShippingContactsRequest.JSON_PROPERTY_BETWEEN_STREETS,
  CustomerUpdateShippingContactsRequest.JSON_PROPERTY_ADDRESS,
  CustomerUpdateShippingContactsRequest.JSON_PROPERTY_PARENT_ID,
  CustomerUpdateShippingContactsRequest.JSON_PROPERTY_DEFAULT,
  CustomerUpdateShippingContactsRequest.JSON_PROPERTY_DELETED
})
@JsonTypeName("customer_update_shipping_contacts_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CustomerUpdateShippingContactsRequest {
  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_RECEIVER = "receiver";
  @javax.annotation.Nullable
  private String receiver;

  public static final String JSON_PROPERTY_BETWEEN_STREETS = "between_streets";
  @javax.annotation.Nullable
  private String betweenStreets;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private CustomerShippingContactsRequestAddress address;

  public static final String JSON_PROPERTY_PARENT_ID = "parent_id";
  @javax.annotation.Nullable
  private String parentId;

  public static final String JSON_PROPERTY_DEFAULT = "default";
  @javax.annotation.Nullable
  private Boolean _default;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @javax.annotation.Nullable
  private Boolean deleted;

  public CustomerUpdateShippingContactsRequest() { 
  }

  public CustomerUpdateShippingContactsRequest phone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Phone contact
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public CustomerUpdateShippingContactsRequest receiver(@javax.annotation.Nullable String receiver) {
    this.receiver = receiver;
    return this;
  }

  /**
   * Name of the person who will receive the order
   * @return receiver
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECEIVER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiver() {
    return receiver;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIVER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceiver(@javax.annotation.Nullable String receiver) {
    this.receiver = receiver;
  }


  public CustomerUpdateShippingContactsRequest betweenStreets(@javax.annotation.Nullable String betweenStreets) {
    this.betweenStreets = betweenStreets;
    return this;
  }

  /**
   * The street names between which the order will be delivered.
   * @return betweenStreets
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BETWEEN_STREETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBetweenStreets() {
    return betweenStreets;
  }


  @JsonProperty(value = JSON_PROPERTY_BETWEEN_STREETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBetweenStreets(@javax.annotation.Nullable String betweenStreets) {
    this.betweenStreets = betweenStreets;
  }


  public CustomerUpdateShippingContactsRequest address(@javax.annotation.Nullable CustomerShippingContactsRequestAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerShippingContactsRequestAddress getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable CustomerShippingContactsRequestAddress address) {
    this.address = address;
  }


  public CustomerUpdateShippingContactsRequest parentId(@javax.annotation.Nullable String parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentId() {
    return parentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentId(@javax.annotation.Nullable String parentId) {
    this.parentId = parentId;
  }


  public CustomerUpdateShippingContactsRequest _default(@javax.annotation.Nullable Boolean _default) {
    this._default = _default;
    return this;
  }

  /**
   * Get _default
   * @return _default
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDefault() {
    return _default;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefault(@javax.annotation.Nullable Boolean _default) {
    this._default = _default;
  }


  public CustomerUpdateShippingContactsRequest deleted(@javax.annotation.Nullable Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * Get deleted
   * @return deleted
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(value = JSON_PROPERTY_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(@javax.annotation.Nullable Boolean deleted) {
    this.deleted = deleted;
  }


  /**
   * Return true if this customer_update_shipping_contacts_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerUpdateShippingContactsRequest customerUpdateShippingContactsRequest = (CustomerUpdateShippingContactsRequest) o;
    return Objects.equals(this.phone, customerUpdateShippingContactsRequest.phone) &&
        Objects.equals(this.receiver, customerUpdateShippingContactsRequest.receiver) &&
        Objects.equals(this.betweenStreets, customerUpdateShippingContactsRequest.betweenStreets) &&
        Objects.equals(this.address, customerUpdateShippingContactsRequest.address) &&
        Objects.equals(this.parentId, customerUpdateShippingContactsRequest.parentId) &&
        Objects.equals(this._default, customerUpdateShippingContactsRequest._default) &&
        Objects.equals(this.deleted, customerUpdateShippingContactsRequest.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, receiver, betweenStreets, address, parentId, _default, deleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerUpdateShippingContactsRequest {\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    betweenStreets: ").append(toIndentedString(betweenStreets)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

