/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.conekta.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * It is a parameter that allows to identify in the response, the type of event that is being generated.
 */
public enum EventTypes {
  
  WEBHOOK_PING("webhook_ping"),
  
  ORDER_PAID("order.paid"),
  
  ORDER_EXPIRED("order.expired"),
  
  ORDER_CANCELED("order.canceled"),
  
  ORDER_PENDING_PAYMENT("order.pending_payment");

  private String value;

  EventTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EventTypes fromValue(String value) {
    for (EventTypes b : EventTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

