/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.conekta.model.Payout;
import com.conekta.model.PayoutOrderRequestCustomerInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.conekta.JSON;


/**
 * a payout order
 */
@JsonPropertyOrder({
  PayoutOrderRequest.JSON_PROPERTY_ALLOWED_PAYOUT_METHODS,
  PayoutOrderRequest.JSON_PROPERTY_AMOUNT,
  PayoutOrderRequest.JSON_PROPERTY_CURRENCY,
  PayoutOrderRequest.JSON_PROPERTY_CUSTOMER_INFO,
  PayoutOrderRequest.JSON_PROPERTY_EXPIRES_AT,
  PayoutOrderRequest.JSON_PROPERTY_METADATA,
  PayoutOrderRequest.JSON_PROPERTY_PAYOUT,
  PayoutOrderRequest.JSON_PROPERTY_REASON
})
@JsonTypeName("payout_order_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class PayoutOrderRequest {
  public static final String JSON_PROPERTY_ALLOWED_PAYOUT_METHODS = "allowed_payout_methods";
  @javax.annotation.Nonnull
  private List<String> allowedPayoutMethods = new ArrayList<>();

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Long amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nonnull
  private String currency = "MXN";

  public static final String JSON_PROPERTY_CUSTOMER_INFO = "customer_info";
  @javax.annotation.Nonnull
  private PayoutOrderRequestCustomerInfo customerInfo;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  @javax.annotation.Nonnull
  private Long expiresAt;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_PAYOUT = "payout";
  @javax.annotation.Nonnull
  private Payout payout;

  public static final String JSON_PROPERTY_REASON = "reason";
  @javax.annotation.Nonnull
  private String reason;

  public PayoutOrderRequest() { 
  }

  public PayoutOrderRequest allowedPayoutMethods(@javax.annotation.Nonnull List<String> allowedPayoutMethods) {
    this.allowedPayoutMethods = allowedPayoutMethods;
    return this;
  }

  public PayoutOrderRequest addAllowedPayoutMethodsItem(String allowedPayoutMethodsItem) {
    if (this.allowedPayoutMethods == null) {
      this.allowedPayoutMethods = new ArrayList<>();
    }
    this.allowedPayoutMethods.add(allowedPayoutMethodsItem);
    return this;
  }

  /**
   * The payout methods that are allowed for the payout order.
   * @return allowedPayoutMethods
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ALLOWED_PAYOUT_METHODS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getAllowedPayoutMethods() {
    return allowedPayoutMethods;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOWED_PAYOUT_METHODS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowedPayoutMethods(@javax.annotation.Nonnull List<String> allowedPayoutMethods) {
    this.allowedPayoutMethods = allowedPayoutMethods;
  }


  public PayoutOrderRequest amount(@javax.annotation.Nonnull Long amount) {
    this.amount = amount;
    return this;
  }

  /**
   * The amount of the payout order.
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Long amount) {
    this.amount = amount;
  }


  public PayoutOrderRequest currency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * The currency in which the payout order is made.
   * @return currency
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public PayoutOrderRequest customerInfo(@javax.annotation.Nonnull PayoutOrderRequestCustomerInfo customerInfo) {
    this.customerInfo = customerInfo;
    return this;
  }

  /**
   * Get customerInfo
   * @return customerInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PayoutOrderRequestCustomerInfo getCustomerInfo() {
    return customerInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerInfo(@javax.annotation.Nonnull PayoutOrderRequestCustomerInfo customerInfo) {
    this.customerInfo = customerInfo;
  }


  public PayoutOrderRequest expiresAt(@javax.annotation.Nonnull Long expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * The expiration time of the payout order in Unix timestamp.
   * @return expiresAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresAt(@javax.annotation.Nonnull Long expiresAt) {
    this.expiresAt = expiresAt;
  }


  public PayoutOrderRequest metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public PayoutOrderRequest putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * The metadata of the payout order.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public PayoutOrderRequest payout(@javax.annotation.Nonnull Payout payout) {
    this.payout = payout;
    return this;
  }

  /**
   * Get payout
   * @return payout
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYOUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Payout getPayout() {
    return payout;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYOUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayout(@javax.annotation.Nonnull Payout payout) {
    this.payout = payout;
  }


  public PayoutOrderRequest reason(@javax.annotation.Nonnull String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * The reason for the payout order.
   * @return reason
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REASON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReason(@javax.annotation.Nonnull String reason) {
    this.reason = reason;
  }


  /**
   * Return true if this payout_order_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayoutOrderRequest payoutOrderRequest = (PayoutOrderRequest) o;
    return Objects.equals(this.allowedPayoutMethods, payoutOrderRequest.allowedPayoutMethods) &&
        Objects.equals(this.amount, payoutOrderRequest.amount) &&
        Objects.equals(this.currency, payoutOrderRequest.currency) &&
        Objects.equals(this.customerInfo, payoutOrderRequest.customerInfo) &&
        Objects.equals(this.expiresAt, payoutOrderRequest.expiresAt) &&
        Objects.equals(this.metadata, payoutOrderRequest.metadata) &&
        Objects.equals(this.payout, payoutOrderRequest.payout) &&
        Objects.equals(this.reason, payoutOrderRequest.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedPayoutMethods, amount, currency, customerInfo, expiresAt, metadata, payout, reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayoutOrderRequest {\n");
    sb.append("    allowedPayoutMethods: ").append(toIndentedString(allowedPayoutMethods)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    customerInfo: ").append(toIndentedString(customerInfo)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    payout: ").append(toIndentedString(payout)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

