/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.conekta.JSON;


/**
 * ShippingLinesDataResponse
 */
@JsonPropertyOrder({
  ShippingLinesDataResponse.JSON_PROPERTY_AMOUNT,
  ShippingLinesDataResponse.JSON_PROPERTY_CARRIER,
  ShippingLinesDataResponse.JSON_PROPERTY_TRACKING_NUMBER,
  ShippingLinesDataResponse.JSON_PROPERTY_METHOD,
  ShippingLinesDataResponse.JSON_PROPERTY_METADATA,
  ShippingLinesDataResponse.JSON_PROPERTY_ID,
  ShippingLinesDataResponse.JSON_PROPERTY_OBJECT,
  ShippingLinesDataResponse.JSON_PROPERTY_PARENT_ID
})
@JsonTypeName("shipping_lines_data_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ShippingLinesDataResponse {
  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Long amount;

  public static final String JSON_PROPERTY_CARRIER = "carrier";
  @javax.annotation.Nullable
  private String carrier;

  public static final String JSON_PROPERTY_TRACKING_NUMBER = "tracking_number";
  @javax.annotation.Nullable
  private String trackingNumber;

  public static final String JSON_PROPERTY_METHOD = "method";
  @javax.annotation.Nullable
  private String method;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nullable
  private String _object;

  public static final String JSON_PROPERTY_PARENT_ID = "parent_id";
  @javax.annotation.Nullable
  private String parentId;

  public ShippingLinesDataResponse() { 
  }

  public ShippingLinesDataResponse amount(@javax.annotation.Nonnull Long amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Shipping amount in cents
   * minimum: 0
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Long amount) {
    this.amount = amount;
  }


  public ShippingLinesDataResponse carrier(@javax.annotation.Nullable String carrier) {
    this.carrier = carrier;
    return this;
  }

  /**
   * Carrier name for the shipment
   * @return carrier
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CARRIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCarrier() {
    return carrier;
  }


  @JsonProperty(value = JSON_PROPERTY_CARRIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCarrier(@javax.annotation.Nullable String carrier) {
    this.carrier = carrier;
  }


  public ShippingLinesDataResponse trackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

  /**
   * Tracking number can be used to track the shipment
   * @return trackingNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACKING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackingNumber() {
    return trackingNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }


  public ShippingLinesDataResponse method(@javax.annotation.Nullable String method) {
    this.method = method;
    return this;
  }

  /**
   * Method of shipment
   * @return method
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMethod() {
    return method;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(@javax.annotation.Nullable String method) {
    this.method = method;
  }


  public ShippingLinesDataResponse metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public ShippingLinesDataResponse putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Hash where the user can send additional information for each &#39;shipping&#39;.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public ShippingLinesDataResponse id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ShippingLinesDataResponse _object(@javax.annotation.Nullable String _object) {
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(@javax.annotation.Nullable String _object) {
    this._object = _object;
  }


  public ShippingLinesDataResponse parentId(@javax.annotation.Nullable String parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentId() {
    return parentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentId(@javax.annotation.Nullable String parentId) {
    this.parentId = parentId;
  }


  /**
   * Return true if this shipping_lines_data_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingLinesDataResponse shippingLinesDataResponse = (ShippingLinesDataResponse) o;
    return Objects.equals(this.amount, shippingLinesDataResponse.amount) &&
        Objects.equals(this.carrier, shippingLinesDataResponse.carrier) &&
        Objects.equals(this.trackingNumber, shippingLinesDataResponse.trackingNumber) &&
        Objects.equals(this.method, shippingLinesDataResponse.method) &&
        Objects.equals(this.metadata, shippingLinesDataResponse.metadata) &&
        Objects.equals(this.id, shippingLinesDataResponse.id) &&
        Objects.equals(this._object, shippingLinesDataResponse._object) &&
        Objects.equals(this.parentId, shippingLinesDataResponse.parentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, carrier, trackingNumber, method, metadata, id, _object, parentId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingLinesDataResponse {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

