/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.conekta.JSON;


/**
 * SubscriptionDetailsCard
 */
@JsonPropertyOrder({
  SubscriptionDetailsCard.JSON_PROPERTY_ID,
  SubscriptionDetailsCard.JSON_PROPERTY_CREATED_AT,
  SubscriptionDetailsCard.JSON_PROPERTY_ACTIVE,
  SubscriptionDetailsCard.JSON_PROPERTY_OBJECT,
  SubscriptionDetailsCard.JSON_PROPERTY_EXP_MONTH,
  SubscriptionDetailsCard.JSON_PROPERTY_EXP_YEAR,
  SubscriptionDetailsCard.JSON_PROPERTY_BRAND,
  SubscriptionDetailsCard.JSON_PROPERTY_LAST4,
  SubscriptionDetailsCard.JSON_PROPERTY_NAME,
  SubscriptionDetailsCard.JSON_PROPERTY_PAYMENT_SOURCE_STATUS,
  SubscriptionDetailsCard.JSON_PROPERTY_CUSTOMER_ID,
  SubscriptionDetailsCard.JSON_PROPERTY_CUSTOMER_CUSTOM_REFERENCE
})
@JsonTypeName("subscription_details_card")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class SubscriptionDetailsCard {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private Long createdAt;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  @javax.annotation.Nullable
  private Boolean active;

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nullable
  private String _object;

  public static final String JSON_PROPERTY_EXP_MONTH = "exp_month";
  @javax.annotation.Nullable
  private String expMonth;

  public static final String JSON_PROPERTY_EXP_YEAR = "exp_year";
  @javax.annotation.Nullable
  private String expYear;

  public static final String JSON_PROPERTY_BRAND = "brand";
  @javax.annotation.Nullable
  private String brand;

  public static final String JSON_PROPERTY_LAST4 = "last4";
  @javax.annotation.Nullable
  private String last4;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PAYMENT_SOURCE_STATUS = "payment_source_status";
  @javax.annotation.Nullable
  private String paymentSourceStatus;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customer_id";
  @javax.annotation.Nullable
  private String customerId;

  public static final String JSON_PROPERTY_CUSTOMER_CUSTOM_REFERENCE = "customer_custom_reference";
  @javax.annotation.Nullable
  private String customerCustomReference;

  public SubscriptionDetailsCard() { 
  }

  public SubscriptionDetailsCard id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public SubscriptionDetailsCard createdAt(@javax.annotation.Nullable Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable Long createdAt) {
    this.createdAt = createdAt;
  }


  public SubscriptionDetailsCard active(@javax.annotation.Nullable Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(@javax.annotation.Nullable Boolean active) {
    this.active = active;
  }


  public SubscriptionDetailsCard _object(@javax.annotation.Nullable String _object) {
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(@javax.annotation.Nullable String _object) {
    this._object = _object;
  }


  public SubscriptionDetailsCard expMonth(@javax.annotation.Nullable String expMonth) {
    this.expMonth = expMonth;
    return this;
  }

  /**
   * Get expMonth
   * @return expMonth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXP_MONTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpMonth() {
    return expMonth;
  }


  @JsonProperty(value = JSON_PROPERTY_EXP_MONTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpMonth(@javax.annotation.Nullable String expMonth) {
    this.expMonth = expMonth;
  }


  public SubscriptionDetailsCard expYear(@javax.annotation.Nullable String expYear) {
    this.expYear = expYear;
    return this;
  }

  /**
   * Get expYear
   * @return expYear
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXP_YEAR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpYear() {
    return expYear;
  }


  @JsonProperty(value = JSON_PROPERTY_EXP_YEAR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpYear(@javax.annotation.Nullable String expYear) {
    this.expYear = expYear;
  }


  public SubscriptionDetailsCard brand(@javax.annotation.Nullable String brand) {
    this.brand = brand;
    return this;
  }

  /**
   * Get brand
   * @return brand
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBrand() {
    return brand;
  }


  @JsonProperty(value = JSON_PROPERTY_BRAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrand(@javax.annotation.Nullable String brand) {
    this.brand = brand;
  }


  public SubscriptionDetailsCard last4(@javax.annotation.Nullable String last4) {
    this.last4 = last4;
    return this;
  }

  /**
   * Get last4
   * @return last4
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST4, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLast4() {
    return last4;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST4, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast4(@javax.annotation.Nullable String last4) {
    this.last4 = last4;
  }


  public SubscriptionDetailsCard name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public SubscriptionDetailsCard paymentSourceStatus(@javax.annotation.Nullable String paymentSourceStatus) {
    this.paymentSourceStatus = paymentSourceStatus;
    return this;
  }

  /**
   * Get paymentSourceStatus
   * @return paymentSourceStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_SOURCE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentSourceStatus() {
    return paymentSourceStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_SOURCE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentSourceStatus(@javax.annotation.Nullable String paymentSourceStatus) {
    this.paymentSourceStatus = paymentSourceStatus;
  }


  public SubscriptionDetailsCard customerId(@javax.annotation.Nullable String customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Get customerId
   * @return customerId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerId() {
    return customerId;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerId(@javax.annotation.Nullable String customerId) {
    this.customerId = customerId;
  }


  public SubscriptionDetailsCard customerCustomReference(@javax.annotation.Nullable String customerCustomReference) {
    this.customerCustomReference = customerCustomReference;
    return this;
  }

  /**
   * Get customerCustomReference
   * @return customerCustomReference
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_CUSTOM_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerCustomReference() {
    return customerCustomReference;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_CUSTOM_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerCustomReference(@javax.annotation.Nullable String customerCustomReference) {
    this.customerCustomReference = customerCustomReference;
  }


  /**
   * Return true if this subscription_details_card object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionDetailsCard subscriptionDetailsCard = (SubscriptionDetailsCard) o;
    return Objects.equals(this.id, subscriptionDetailsCard.id) &&
        Objects.equals(this.createdAt, subscriptionDetailsCard.createdAt) &&
        Objects.equals(this.active, subscriptionDetailsCard.active) &&
        Objects.equals(this._object, subscriptionDetailsCard._object) &&
        Objects.equals(this.expMonth, subscriptionDetailsCard.expMonth) &&
        Objects.equals(this.expYear, subscriptionDetailsCard.expYear) &&
        Objects.equals(this.brand, subscriptionDetailsCard.brand) &&
        Objects.equals(this.last4, subscriptionDetailsCard.last4) &&
        Objects.equals(this.name, subscriptionDetailsCard.name) &&
        Objects.equals(this.paymentSourceStatus, subscriptionDetailsCard.paymentSourceStatus) &&
        Objects.equals(this.customerId, subscriptionDetailsCard.customerId) &&
        Objects.equals(this.customerCustomReference, subscriptionDetailsCard.customerCustomReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, active, _object, expMonth, expYear, brand, last4, name, paymentSourceStatus, customerId, customerCustomReference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionDetailsCard {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    expMonth: ").append(toIndentedString(expMonth)).append("\n");
    sb.append("    expYear: ").append(toIndentedString(expYear)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    last4: ").append(toIndentedString(last4)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    paymentSourceStatus: ").append(toIndentedString(paymentSourceStatus)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    customerCustomReference: ").append(toIndentedString(customerCustomReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

