/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.conekta;

import com.conekta.model.BlacklistRuleResponse;
import com.conekta.model.CreateRuleWhitelistRequest;
import com.conekta.model.DeletedBlacklistRuleResponse;
import com.conekta.model.DeletedWhitelistRuleResponse;
import com.conekta.model.RiskRulesList;
import com.conekta.model.WhitelistlistRuleResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * API tests for AntifraudApi
 */
public class AntifraudApiTest {

    private final AntifraudApi api = new AntifraudApi(TestUtils.apiClient());

    @Test
    public void createRuleBlacklistTest() throws ApiException {
        CreateRuleWhitelistRequest createRuleWhitelistRequest = new CreateRuleWhitelistRequest()
                .field("email")
                .value("fcarrero_black@gmail.com")
                .description("Test");
        BlacklistRuleResponse response = api.createRuleBlacklist(createRuleWhitelistRequest, "es");
        Assertions.assertNotNull(response);
    }

    @Test
    public void createRuleWhitelistTest() throws ApiException {
        CreateRuleWhitelistRequest createRuleWhitelistRequest = new CreateRuleWhitelistRequest()
                .field("email")
                .value("fcarrero@gmail.com")
                .description("Test");
        WhitelistlistRuleResponse response = api.createRuleWhitelist("es", createRuleWhitelistRequest);
        Assertions.assertNotNull(response);
    }

    @Test
    public void deleteRuleBlacklistTest() throws ApiException {
        DeletedBlacklistRuleResponse response = api.deleteRuleBlacklist("618c3f2fdb8b8da9be376b1e", "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void deleteRuleWhitelistTest() throws ApiException {
        DeletedWhitelistRuleResponse response = api.deleteRuleWhitelist("618c3f2fdb8b8da9be376afe", "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void getRuleBlacklistTest() throws ApiException {
        RiskRulesList response = api.getRuleBlacklist("es");
        Assertions.assertNotNull(response);
    }

    @Test
    public void getRuleWhitelistTest() throws ApiException {
        RiskRulesList response = api.getRuleWhitelist("es");
        Assertions.assertNotNull(response);
    }

}
