/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta;

import com.conekta.*;
import com.conekta.auth.*;
import com.conekta.model.ChargeOrderResponse;
import com.conekta.model.ChargeRequest;
import com.conekta.model.ChargeRequestPaymentMethod;
import com.conekta.model.ChargeResponse;
import com.conekta.model.ChargeUpdateRequest;
import com.conekta.model.ChargesOrderResponse;
import com.conekta.model.Error;
import com.conekta.model.GetChargesResponse;
import com.conekta.model.PaymentMethodGeneralRequest;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChargesApi
 */
public class ChargesApiTest {

    private final ChargesApi api = new ChargesApi(TestUtils.apiClient());

    private ChargeRequest buildCashChargeRequest() {
        ChargeRequestPaymentMethod paymentMethod = new ChargeRequestPaymentMethod();
        paymentMethod.setActualInstance(new PaymentMethodGeneralRequest().type("cash"));
        return new ChargeRequest()
                .amount(1000L)
                .paymentMethod(paymentMethod);
    }

    @Test
    public void getChargesTest() throws ApiException {
        GetChargesResponse response = api.getCharges("es", null, 20, null, null, null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void ordersCreateChargeTest() throws ApiException {
        ChargeOrderResponse response = api.ordersCreateCharge(
                "ord_2tVKxbhNzfUnGjnXG",
                buildCashChargeRequest(),
                "es",
                null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void ordersCreateChargesTest() throws ApiException {
        ChargesOrderResponse response = api.ordersCreateCharges(
                "ord_2wrW9arie9fUG4MfD",
                buildCashChargeRequest(),
                "es",
                null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void updateChargeTest() throws ApiException {
        ChargeUpdateRequest chargeUpdateRequest = new ChargeUpdateRequest().referenceId("ref_9876");
        ChargeResponse response = api.updateCharge("6524722f28c7ba0016a5b17d", chargeUpdateRequest, "es", null);
        Assertions.assertNotNull(response);
    }

}
