/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.conekta;

import com.conekta.model.ChargeRequest;
import com.conekta.model.ChargeRequestPaymentMethod;
import com.conekta.model.CustomerInfoCustomerId;
import com.conekta.model.GetOrdersResponse;
import com.conekta.model.OrderCaptureRequest;
import com.conekta.model.OrderRefundRequest;
import com.conekta.model.OrderRequest;
import com.conekta.model.OrderRequestCustomerInfo;
import com.conekta.model.OrderResponse;
import com.conekta.model.OrderUpdate;
import com.conekta.model.PaymentMethodGeneralRequest;
import com.conekta.model.Product;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for OrdersApi
 */
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi(TestUtils.apiClient());

    @Disabled("Mockoon sample response body has malformed tax_lines that fails SDK deserialization")
    @Test
    public void cancelOrderTest() throws ApiException {
        OrderResponse response = api.cancelOrder("ord_2tqaGQYZyvBsMKEgs", "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void createOrderTest() throws ApiException {
        ChargeRequestPaymentMethod paymentMethod = new ChargeRequestPaymentMethod();
        paymentMethod.setActualInstance(
                new PaymentMethodGeneralRequest().type("card").tokenId("tok_2znsHppi6bHeDPSHi"));

        OrderRequestCustomerInfo customerInfo = new OrderRequestCustomerInfo();
        customerInfo.setActualInstance(new CustomerInfoCustomerId().customerId("cus_2tKcHxhTz7xU5SymF"));

        OrderRequest orderRequest = new OrderRequest()
                .currency("MXN")
                .threeDsMode("smart")
                .customerInfo(customerInfo)
                .addChargesItem(new ChargeRequest().amount(1000L).paymentMethod(paymentMethod))
                .addLineItemsItem(new Product().name("test").quantity(1).unitPrice(1000));
        OrderResponse response = api.createOrder(orderRequest, "es", null);
        Assertions.assertAll("created order",
                () -> Assertions.assertNotNull(response),
                () -> Assertions.assertNotNull(response.getId()),
                () -> Assertions.assertEquals("order", response.getObject()),
                () -> Assertions.assertEquals("MXN", response.getCurrency()),
                () -> Assertions.assertEquals("paid", response.getPaymentStatus()),
                () -> Assertions.assertNotNull(response.getCharges()),
                () -> Assertions.assertNotNull(response.getCharges().getData()),
                () -> Assertions.assertFalse(response.getCharges().getData().isEmpty()));
    }

    @Test
    public void getOrderByIdTest() throws ApiException {
        OrderResponse response = api.getOrderById("ord_2tUyGSk9TNWUcyvjn", "es", null);
        Assertions.assertAll("order by id",
                () -> Assertions.assertNotNull(response),
                () -> Assertions.assertNotNull(response.getId()),
                () -> Assertions.assertEquals("order", response.getObject()),
                () -> Assertions.assertEquals("MXN", response.getCurrency()),
                () -> Assertions.assertEquals(10000, response.getAmount()),
                () -> Assertions.assertEquals(0, response.getAmountRefunded()),
                () -> Assertions.assertEquals("pending_payment", response.getPaymentStatus()));
    }

    @Disabled("Mockoon sample response body has malformed tax_lines that fails SDK deserialization")
    @Test
    public void getOrdersTest() throws ApiException {
        GetOrdersResponse response = api.getOrders(
                "es", null, 20, null, null, null, null, null, null, null, null, null, null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void orderCancelRefundTest() throws ApiException {
        String orderId = "ord_2tV52JvSom2w3E8bX";
        OrderResponse response = api.orderCancelRefund(orderId, "ref_test_01", "es", null);
        Assertions.assertAll("cancel refund",
                () -> Assertions.assertNotNull(response),
                () -> Assertions.assertEquals(orderId, response.getId()),
                () -> Assertions.assertEquals("order", response.getObject()),
                () -> Assertions.assertEquals("MXN", response.getCurrency()));
    }

    @Test
    public void orderRefundTest() throws ApiException {
        String orderId = "ord_2tV52JvSom2w3E8bX";
        OrderRefundRequest orderRefundRequest = new OrderRefundRequest()
                .amount(1000)
                .reason("requested_by_client");
        OrderResponse response = api.orderRefund(orderId, orderRefundRequest, "es", null);
        Assertions.assertAll("refund",
                () -> Assertions.assertNotNull(response),
                () -> Assertions.assertEquals(orderId, response.getId()),
                () -> Assertions.assertEquals("order", response.getObject()),
                () -> Assertions.assertEquals("MXN", response.getCurrency()),
                () -> Assertions.assertEquals("partially_refunded", response.getPaymentStatus()),
                () -> Assertions.assertTrue(response.getAmountRefunded() > 0));
    }

    @Test
    public void ordersCreateCaptureTest() throws ApiException {
        String orderId = "ord_2tVKoTd79XK1GqJme";
        OrderCaptureRequest orderCaptureRequest = new OrderCaptureRequest().amount(1000L);
        OrderResponse response = api.ordersCreateCapture(orderId, "es", null, orderCaptureRequest);
        Assertions.assertAll("capture",
                () -> Assertions.assertNotNull(response),
                () -> Assertions.assertEquals(orderId, response.getId()),
                () -> Assertions.assertEquals("order", response.getObject()),
                () -> Assertions.assertEquals("paid", response.getPaymentStatus()),
                () -> Assertions.assertEquals(40000, response.getAmount()),
                () -> Assertions.assertEquals("MXN", response.getCurrency()));
    }

    @Test
    public void updateOrderTest() throws ApiException {
        String orderId = "ord_2tVPCGRXnMXKdvcsj";
        OrderUpdate orderUpdate = new OrderUpdate().currency("MXN");
        OrderResponse response = api.updateOrder(orderId, orderUpdate, "es");
        Assertions.assertAll("update order",
                () -> Assertions.assertNotNull(response),
                () -> Assertions.assertEquals(orderId, response.getId()),
                () -> Assertions.assertEquals("order", response.getObject()),
                () -> Assertions.assertEquals("MXN", response.getCurrency()),
                () -> Assertions.assertEquals(82000, response.getAmount()),
                () -> Assertions.assertFalse(response.getIsRefundable()));
    }

}
