/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta;

import com.conekta.*;
import com.conekta.auth.*;
import com.conekta.model.Error;
import com.conekta.model.GetPlansResponse;
import com.conekta.model.PlanRequest;
import com.conekta.model.PlanResponse;
import com.conekta.model.PlanUpdateRequest;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlansApi
 */
public class PlansApiTest {

    private final PlansApi api = new PlansApi(new ApiClient().setBasePath(Utils.getBasePath()));

    /**
     * Create Plan
     *
     * Create a new plan for an existing order
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPlanTest() throws ApiException {
        PlanRequest planRequest = new PlanRequest();
        planRequest.setAmount(1000);
        planRequest.setCurrency("MXN");
        planRequest.setName("Test");
        String acceptLanguage = "es";
        PlanResponse response = api.createPlan(planRequest, acceptLanguage, null);
        Assertions.assertNotNull(response);
    }

    /**
     * Delete Plan
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePlanTest() throws ApiException {
        String id = "plan_2tZb5q8Z3PYpg6SJd";
        String acceptLanguage = "es";
        PlanResponse response = api.deletePlan(id, acceptLanguage);
        Assertions.assertNotNull(response);
    }

    /**
     * Get Plan
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlanTest() throws ApiException {
        String id = "plan_2tZb5q8Z3PYpg6SJd";
        String acceptLanguage = "es";
        PlanResponse response = api.getPlan(id, acceptLanguage, null);
        Assertions.assertNotNull(response);
    }

    /**
     * Get A List of Plans
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlansTest() throws ApiException {
        String acceptLanguage = "es";
        Integer limit = 20;
        GetPlansResponse response = api.getPlans(acceptLanguage, null, limit, null, null, null);
        Assertions.assertNotNull(response);
    }

    /**
     * Update Plan
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePlanTest() throws ApiException {
        String id = "plan_2tZb5q8Z3PYpg6SJd";
        PlanUpdateRequest planUpdateRequest = new PlanUpdateRequest();
        planUpdateRequest.setAmount(1500);
        String acceptLanguage = "es";
        PlanResponse response = api.updatePlan(id, planUpdateRequest, acceptLanguage, null);
        Assertions.assertNotNull(response);
    }

}
