/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta;

import com.conekta.*;
import com.conekta.auth.*;
import com.conekta.model.CustomerShippingContactsRequest;
import com.conekta.model.CustomerShippingContactsRequestAddress;
import com.conekta.model.CustomerShippingContactsResponse;
import com.conekta.model.CustomerUpdateShippingContactsRequest;
import com.conekta.model.Error;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShippingContactsApi
 */
public class ShippingContactsApiTest {

    private final ShippingContactsApi api = new ShippingContactsApi(TestUtils.apiClient());

    private CustomerShippingContactsRequestAddress sampleAddress() {
        return new CustomerShippingContactsRequestAddress()
                .city("CDMX")
                .country("mx")
                .postalCode("06100")
                .state("CDMX")
                .street1("Calle 123");
    }

    @Test
    public void createCustomerShippingContactsTest() throws ApiException {
        CustomerShippingContactsRequest customerShippingContactsRequest = new CustomerShippingContactsRequest()
                .phone("1234567890")
                .receiver("Receiver")
                .address(sampleAddress());
        CustomerShippingContactsResponse response = api.createCustomerShippingContacts(
                "cus_2tXyF9BwPG14UMkkg", customerShippingContactsRequest, "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void deleteCustomerShippingContactsTest() throws ApiException {
        CustomerShippingContactsResponse response = api.deleteCustomerShippingContacts(
                "cus_2tZWxbTPtQgGJGh8P", "ship_cont_2tZWzJPBf87C6TcoQ", "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void updateCustomerShippingContactsTest() throws ApiException {
        CustomerUpdateShippingContactsRequest customerUpdateShippingContactsRequest =
                new CustomerUpdateShippingContactsRequest()
                        .phone("+5215555555555")
                        .receiver("Updated Receiver");
        CustomerShippingContactsResponse response = api.updateCustomerShippingContacts(
                "cus_2tZWxbTPtQgGJGh8P", "ship_cont_2tZWzJPBf87C6TcoQ",
                customerUpdateShippingContactsRequest, "es", null);
        Assertions.assertNotNull(response);
    }

}
