/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta;

import com.conekta.*;
import com.conekta.auth.*;
import com.conekta.model.Error;
import com.conekta.model.ShippingOrderResponse;
import com.conekta.model.ShippingRequest;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShippingsApi
 */
public class ShippingsApiTest {

    private static final String ORDER_ID = "ord_2tVyWPnCPWbrV37mW";
    private static final String SHIPPING_ID = "ship_lin_2tVzNuDGSaDwreMg6";

    private final ShippingsApi api = new ShippingsApi(TestUtils.apiClient());

    private ShippingRequest buildShippingRequest() {
        return new ShippingRequest()
                .amount(550L)
                .method("Standard")
                .carrier("Conekta")
                .trackingNumber("1234567890");
    }

    @Test
    public void ordersCreateShippingTest() throws ApiException {
        ShippingOrderResponse response = api.ordersCreateShipping(ORDER_ID, buildShippingRequest(), "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void ordersDeleteShippingTest() throws ApiException {
        ShippingOrderResponse response = api.ordersDeleteShipping(ORDER_ID, SHIPPING_ID, "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void ordersUpdateShippingTest() throws ApiException {
        ShippingOrderResponse response = api.ordersUpdateShipping(ORDER_ID, SHIPPING_ID, buildShippingRequest(), "es", null);
        Assertions.assertNotNull(response);
    }

}
