/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta;

import com.conekta.*;
import com.conekta.auth.*;
import com.conekta.model.CustomerPortalResponse;
import com.conekta.model.Error;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionsCustomerPortalApi
 */
public class SubscriptionsCustomerPortalApiTest {

    private final SubscriptionsCustomerPortalApi api = new SubscriptionsCustomerPortalApi(TestUtils.apiClient());

    @Disabled("endpoint POST /subscriptions/{subscription_id}/customer_portal not provided by Mockoon mock")
    @Test
    public void createCustomerPortalTest() throws ApiException {
        CustomerPortalResponse response = api.createCustomerPortal("sub_test", "es", null);
        Assertions.assertNotNull(response);
    }

    @Disabled("endpoint GET /subscriptions/{subscription_id}/customer_portal not provided by Mockoon mock")
    @Test
    public void getCustomerPortalTest() throws ApiException {
        CustomerPortalResponse response = api.getCustomerPortal("sub_test", "es", null);
        Assertions.assertNotNull(response);
    }

}
