/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta;

import com.conekta.*;
import com.conekta.auth.*;
import com.conekta.model.Error;
import com.conekta.model.OrderTaxRequest;
import com.conekta.model.OrderTaxResponse;
import com.conekta.model.OrdersUpdateTaxesRequest;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TaxesApi
 */
public class TaxesApiTest {

    private static final String ORDER_ID = "ord_2tVyWPnCPWbrV37mW";
    private static final String TAX_ID = "tax_lin_2tVzVp6AAptCRHhgt";

    private final TaxesApi api = new TaxesApi(TestUtils.apiClient());

    @Test
    public void ordersCreateTaxesTest() throws ApiException {
        OrderTaxRequest orderTaxRequest = new OrderTaxRequest().amount(160L).description("IVA");
        OrderTaxResponse response = api.ordersCreateTaxes(ORDER_ID, orderTaxRequest, "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void ordersDeleteTaxesTest() throws ApiException {
        OrderTaxResponse response = api.ordersDeleteTaxes(ORDER_ID, TAX_ID, "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void ordersUpdateTaxesTest() throws ApiException {
        OrdersUpdateTaxesRequest ordersUpdateTaxesRequest = new OrdersUpdateTaxesRequest().amount(200L);
        OrderTaxResponse response = api.ordersUpdateTaxes(ORDER_ID, TAX_ID, ordersUpdateTaxesRequest, "es", null);
        Assertions.assertNotNull(response);
    }

}
