/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta;

import com.conekta.*;
import com.conekta.auth.*;
import com.conekta.model.Error;
import com.conekta.model.TokenRequest;
import com.conekta.model.TokenRequestCheckout;
import com.conekta.model.TokenResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokensApi
 */
public class TokensApiTest {

    private final TokensApi api = new TokensApi(TestUtils.apiClient());

    @Test
    public void createTokenTest() throws ApiException {
        TokenRequest tokenRequest = new TokenRequest()
                .checkout(new TokenRequestCheckout().returnsControlOn("Token"));
        TokenResponse response = api.createToken(tokenRequest, "es");
        Assertions.assertNotNull(response);
    }

}
