/*
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.conekta;

import com.conekta.*;
import com.conekta.auth.*;
import com.conekta.model.Error;
import com.conekta.model.GetTransactionsResponse;
import com.conekta.model.TransactionResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionsApi
 */
public class TransactionsApiTest {

    private final TransactionsApi api = new TransactionsApi(TestUtils.apiClient());

    @Test
    public void getTransactionTest() throws ApiException {
        TransactionResponse response = api.getTransaction("6456b6dfac0fd40001a64eb8", "es", null);
        Assertions.assertNotNull(response);
    }

    @Test
    public void getTransactionsTest() throws ApiException {
        GetTransactionsResponse response = api.getTransactions(
                "es", null, 2, null, null, null, null, null, null);
        Assertions.assertNotNull(response);
    }

}
